version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        container_name: app
        volumes:
            - /app/node_modules
            - /front:/app
        environment:
            - TZ=Asia/Seoul
            - LC_ALL=C.UTF-8
